import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import 'tailwindcss/tailwind.css'
import { Header } from '../components/Header'
import { Hero } from '../components/Hero'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
    </div>
  )
}
